[SOC - PowerShell Activity]
search = index=* source="WinEventLog:Microsoft-Windows-PowerShell/Operational"
description = Detects PowerShell activity collected from the Windows PowerShell Operational log.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1

[SOC - Sysmon DNS Query]
search = index=* source="WinEventLog:Microsoft-Windows-Sysmon/Operational" EventCode=22
description = Detects DNS query activity using Sysmon Event ID 22.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1

[SOC - Sysmon File Creation]
search = index=* source="WinEventLog:Microsoft-Windows-Sysmon/Operational" EventCode=11
description = Detects file creation activity using Sysmon Event ID 11.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1

[SOC - Sysmon Network Connection]
search = index=* source="WinEventLog:Microsoft-Windows-Sysmon/Operational" EventCode=3
description = Detects network connection activity using Sysmon Event ID 3.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1

[SOC - Sysmon Process Creation]
search = index=* source="WinEventLog:Microsoft-Windows-Sysmon/Operational" EventCode=1
description = Detects process creation activity using Sysmon Event ID 1.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1

[SOC - Sysmon Registry Activity]
search = index=* source="WinEventLog:Microsoft-Windows-Sysmon/Operational" EventCode IN (12,13,14)
description = Detects registry activity using Sysmon Event IDs 12, 13 and 14.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1

[SOC - Windows Failed Logon]
search = index=* EventCode=4625
description = Detects failed Windows authentication attempts using Security Event ID 4625.
cron_schedule = */5 * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
disabled = 0
enableSched = 1
