# Collect Sysmon Operational events
[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = main
renderXml = false
start_from = oldest

# Collect PowerShell Operational events
[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = main
renderXml = false
start_from = oldest
